services:
  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "6543:5432"
    command: >
      bash -c "
        docker-entrypoint.sh postgres &
        until pg_isready -U postgres; do sleep 1; done;
        psql -U postgres -c 'CREATE DATABASE appdb_dev;' || true;
        wait
      "
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
