services:
  app:
    build: .
    container_name: my-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    container_name: my-postgres
    ports:
      - "6543:5432"
    env_file:
      - .env
    command: >
      bash -c "
        docker-entrypoint.sh postgres &
        until pg_isready -U postgres; do sleep 1; done;
        psql -U postgres -c 'CREATE DATABASE appdb_dev;' || true;
        wait
      "
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
